// 🌍 SmartWerk Multilanguage Configuration
window.translations = {
  en: {
    menu: "Menu",
    back_dashboard: "Back to Dashboard",
    home: "Home",
    clients: "Clients",
    create_client: "Create Client",
    saved_clients: "Saved Clients",
    invoices: "Invoices",
    create_invoice: "Create Invoice",
    saved_invoices: "Saved Invoices",
    quotes: "Quotes",
    create_quote: "Create Quote",
    saved_quotes: "Saved Quotes",
    contracts: "Contracts",
    create_contract: "Create Contract",
    saved_contracts: "Saved Contracts",
    reminders: "Reminders",
    create_reminder: "Create Reminder",
    saved_reminders: "Saved Reminders",
    expense_csv: "Expense CSV",
    create_expense: "Create Expense",
    saved_expenses: "Saved Expenses",
    analytics: "Analytics",
    bookkeeper: "My Bookkeeper",
    summary: "Summary",
    roi: "ROI Estimator",
    taxassistant: "Tax Assistant",
    tax_calculator: "Tax Calculator",
    tax_analytics: "Tax Analytics",
    tax_guide: "Tax Guide",
    templates: "Templates",
    email_gemeente: "Email to Gemeente",
    cv: "CV / Portfolio",
    ai_assistant: "AI Assistant (PRO)",
    settings: "Settings",
    profile: "Profile",
    toggle_theme: "Toggle Theme",
    help: "Help",
    upgrade: "Upgrade to PRO",
    contact: "Contact Support",
    logout: "Logout",
    welcome: "Welcome",
    plan_free: "Free",
    quick_clients: "Clients",
    quick_invoice: "Invoice",
    quick_quote: "Quote",
    quick_contract: "Contract",
    quick_reminder: "Reminder",
    revenue: "Revenue",
    unpaid: "Unpaid",
    quote_rate: "Quote Win-Rate",
    reminders_sent: "Reminders Sent",
    expenses: "Expenses",
    overdue: "Overdue",
    top_client: "Top Client",
    smart_suggestions: "Smart Suggestions",
    suggestion_all_good: "✅ All good. Keep it up!",
    suggestion_overdue_invoices: "📌 {count} overdue invoices — send reminders.",
    suggestion_no_reminders: "⚠️ Overdue invoices exist but no reminders sent.",
    suggestion_low_winrate: "📉 Low quote win rate — optimize your offers.",
    suggestion_expenses_over: "📊 Expenses exceed revenue this month.",
    recent_activity: "Recent Activity",
    loading: "Loading...",
    chart_title: "Revenue",
    chart_labels: {
      draft: "Draft",
      sent: "Sent",
      paid: "Paid",
      overdue: "Overdue"
    },
    activity_types: {
      navigation: "Navigation",
      invoice: "Invoice",
      event: "Event"
    },
    activity_messages: {
      "created clients": "Created clients",
      "created reminder": "Created reminder",
      "invoice inv-2025-027 updated": "Invoice INV-2025-027 updated"
    }
  },

  nl: {
    menu: "Menu",
    back_dashboard: "Terug naar dashboard",
    home: "Home",
    clients: "Klanten",
    create_client: "Klant aanmaken",
    saved_clients: "Opgeslagen klanten",
    invoices: "Facturen",
    create_invoice: "Factuur aanmaken",
    saved_invoices: "Opgeslagen facturen",
    quotes: "Offertes",
    create_quote: "Offerte aanmaken",
    saved_quotes: "Opgeslagen offertes",
    contracts: "Contracten",
    create_contract: "Contract aanmaken",
    saved_contracts: "Opgeslagen contracten",
    reminders: "Herinneringen",
    create_reminder: "Herinnering aanmaken",
    saved_reminders: "Opgeslagen herinneringen",
    expense_csv: "Onkosten CSV",
    create_expense: "Maak kosten aan",
    saved_expenses: "Opgeslagen kosten",
    analytics: "Analytics",
    my_bookkeeper: "Mijn boekhouder",
    summary: "Overzicht",
    roi_estimator: "ROI-calculator",
    tax_assistant: "Belastingassistent",
    tax_calculator: "Belastingcalculator",
    tax_analytics: "Belastinganalyse",
    tax_guide: "Belastinggids",
    templates: "Sjablonen",
    email_gemeente: "E-mail naar gemeente",
    cv_portfolio: "CV / Portfolio",
    ai_assistant: "AI Assistent (PRO)",
    settings: "Instellingen",
    profile: "Profiel",
    toggle_theme: "Thema wisselen",
    help: "Hulp",
    upgrade_pro: "Upgraden naar PRO",
    contact_support: "Neem contact op met Support",
    logout: "Uitloggen",
    welcome: "Welkom",
    plan_free: "Gratis",
    quick_clients: "Klanten",
    quick_invoice: "Factuur",
    quick_quote: "Offerte",
    quick_contract: "Contract",
    quick_reminder: "Herinnering",
    revenue: "Inkomsten",
    unpaid: "Onbetaald",
    quote_rate: "Winstpercentage offerte",
    reminders_sent: "Verzonden herinneringen",
    expenses: "Uitgaven",
    overdue: "Achterstallig",
    top_client: "Topklant",
    smart_suggestions: "Slimme suggesties",
    suggestion_all_good: "✅ Alles goed. Ga zo door!",
    suggestion_overdue_invoices: "📌 {count} achterstallige facturen — stuur herinneringen.",
    suggestion_no_reminders: "⚠️ Achterstallige facturen maar geen herinneringen verzonden.",
    suggestion_low_winrate: "📉 Lage offerte-succesratio — optimaliseer je aanbiedingen.",
    suggestion_expenses_over: "📊 Uitgaven overschrijden de inkomsten deze maand.",
    recent_activity: "Recente activiteit",
    loading: "Laden...",
    chart_title: "Inkomsten",
    chart_labels: {
      draft: "Concept",
      sent: "Verzonden",
      paid: "Betaald",
      overdue: "Achterstallig"
    },
    activity_types: {
      navigation: "Navigatie",
      invoice: "Factuur",
      event: "Gebeurtenis"
    },
    activity_messages: {
      "created clients": "Klanten aangemaakt",
      "created reminder": "Herinnering aangemaakt",
      "invoice inv-2025-027 updated": "Factuur INV-2025-027 bijgewerkt"
    }
  },

  de: {
    menu: "Menü",
    back_dashboard: "Zurück zum Dashboard",
    home: "Startseite",
    clients: "Kunden",
    invoices: "Rechnungen",
    quotes: "Angebote",
    contracts: "Verträge",
    reminders: "Erinnerungen",
    expense_csv: "Ausgaben CSV",
    analytics: "Analytik",
    tax_assistant: "Steuerassistent",
    templates: "Vorlagen",
    settings: "Einstellungen",
    help: "Hilfe",
    logout: "Abmelden",
    welcome: "Willkommen",
    revenue: "Einnahmen",
    unpaid: "Unbezahlt",
    overdue: "Überfällig",
    expenses: "Ausgaben",
    suggestion_all_good: "✅ Alles gut. Weiter so!",
    chart_title: "Einnahmen",
    chart_labels: { draft: "Entwurf", sent: "Gesendet", paid: "Bezahlt", overdue: "Überfällig" }
  },

  fr: {
    menu: "Menu",
    back_dashboard: "Retour au tableau de bord",
    home: "Accueil",
    clients: "Clients",
    invoices: "Factures",
    quotes: "Devis",
    contracts: "Contrats",
    reminders: "Rappels",
    expense_csv: "Dépenses CSV",
    analytics: "Analytique",
    tax_assistant: "Assistant fiscal",
    templates: "Modèles",
    settings: "Paramètres",
    help: "Aide",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    revenue: "Revenu",
    unpaid: "Impayé",
    overdue: "En retard",
    expenses: "Dépenses",
    suggestion_all_good: "✅ Tout va bien. Continuez comme ça !",
    chart_title: "Revenu",
    chart_labels: { draft: "Brouillon", sent: "Envoyé", paid: "Payé", overdue: "En retard" }
  },

  pl: {
    menu: "Menu",
    back_dashboard: "Powrót do panelu",
    home: "Strona główna",
    clients: "Klienci",
    invoices: "Faktury",
    quotes: "Oferty",
    contracts: "Umowy",
    reminders: "Przypomnienia",
    expense_csv: "Wydatki CSV",
    analytics: "Analiza",
    tax_assistant: "Asystent podatkowy",
    templates: "Szablony",
    settings: "Ustawienia",
    help: "Pomoc",
    logout: "Wyloguj",
    welcome: "Witamy",
    revenue: "Przychody",
    unpaid: "Niezapłacone",
    overdue: "Zaległe",
    expenses: "Wydatki",
    suggestion_all_good: "✅ Wszystko dobrze. Tak trzymać!",
    chart_title: "Przychody",
    chart_labels: { draft: "Szkic", sent: "Wysłane", paid: "Opłacone", overdue: "Zaległe" }
  },

  ru: {
    menu: "Меню",
    back_dashboard: "Назад к панели",
    home: "Главная",
    clients: "Клиенты",
    create_client: "Создать клиента",
    saved_clients: "Сохраненные клиенты",
    invoices: "Счета",
    create_invoice: "Создать счет",
    saved_invoices: "Сохраненные счета",
    quotes: "Предложения",
    create_quote: "Создать Предложения",
    saved_quotes: "Сохраненные Предложения",
    contracts: "Договоры",
    create_contract: "Создать договор",
    saved_contracts: "Сохраненные договоры",
    reminders: "Напоминания",
    create_reminder: "Создать напоминание",
    saved_reminders: "Сохраненные напоминания",
    expense_csv: "Расходы CSV",
    create_expense: "Создать расход",
    saved_expenses: "Сохраненные расходы",
    analytics: "Аналитика",
    bookkeeper: "Мой бухгалтер",
    summary: "Сводка",
    roi: "Оценщик рентабельности инвестиций",
    tax_assistant: "Налоговый помощник",
    tax_calculator: "Налоговый калькулятор",
    tax_analytics: "Налоговая аналитика",
    tax_guide: "Налоговое руководство",
    templates: "Шаблоны",
    email_gemeente: "Отправить по электронной почте Gemeente",
    cv: "Резюме/Портфолио",
    ai_assistant: "ИИ-помощник (PRO)",
    settings: "Настройки",
    profile: "Профиль",
    toggle_theme: "Переключить тему",
    help: "Помощь",
    upgrade: "Перейти на PRO",
    contact: "Связаться со службой поддержки",
    logout: "Выйти",
    welcome: "Добро пожаловать",
    plan_free: "Бесплатно",
    quick_clients: "Создать клиента",
    quick_invoice: "Создать счет",
    quick_quote: "Создать Предложения",
    quick_contract: "Создать договор",
    quick_reminder: "Создать напоминание",
    revenue: "Доход",
    unpaid: "Неоплачено",
    quote_rate: "Процент успешных заявок",
    reminders_sent: "Отправлено напоминаний",
    overdue: "Просрочено",
    expenses: "Расходы",
    top_client: "Лучший клиент",
    suggestion_all_good: "✅ Всё хорошо. Так держать!",
    suggestion_overdue_invoices: "📌 {считать} просроченных счетов — отправлять напоминания.",
    suggestion_no_reminders: "⚠️ Есть просроченные счета, но напоминания не отправлены.",
    suggestion_low_winrate: "📉 Низкая оценка rate — оптимизируйте свои предложения.",
    suggestion_expenses_over: "📊 Расходы превышают выручку в этом месяце.",
     recent_activity: "Недавняя активность",
    loading: "Загрузка...",
    chart_title: "Доход",
    chart_labels: { draft: "Черновик", sent: "Отправлено", paid: "Оплачено", overdue: "Просрочено" },
    activity_types: { navigation: "Навигация",invoice: "Счет",event: "Событие" },
    activity_messages: {"created clients": "Создано клиентов", "created reminder": "Создано напоминание",
      "invoice inv-2025-027 updated": "Счет INV-2025-027 обновлено" }
  },

  es: {
    menu: "Menú",
    back_dashboard: "Volver al panel",
    home: "Inicio",
    clients: "Clientes",
    invoices: "Facturas",
    quotes: "Presupuestos",
    contracts: "Contratos",
    reminders: "Recordatorios",
    expense_csv: "Gastos CSV",
    analytics: "Analítica",
    tax_assistant: "Asistente Fiscal",
    templates: "Plantillas",
    settings: "Configuración",
    help: "Ayuda",
    logout: "Cerrar sesión",
    welcome: "Bienvenido",
    revenue: "Ingresos",
    unpaid: "No pagado",
    overdue: "Atrasado",
    expenses: "Gastos",
    suggestion_all_good: "✅ Todo bien. ¡Sigue así!",
    chart_title: "Ingresos",
    chart_labels: { draft: "Borrador", sent: "Enviado", paid: "Pagado", overdue: "Atrasado" }
  }
};

// 🧠 Apply Translations
function applyTranslations(lang = "en") {
  const dict = window.translations[lang] || window.translations["en"];
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) el.textContent = dict[key];
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const selectedLang = localStorage.getItem("language") || "en";
  applyTranslations(selectedLang);

  const langSelector = document.getElementById("languageSwitcher");
  if (langSelector) {
    langSelector.value = selectedLang;
    langSelector.addEventListener("change", function () {
      localStorage.setItem("language", this.value);
      location.reload();
    });
  }
});
