// 🌍 SmartWerk Multilanguage Configuration
window.translations = {
  en: {
    menu: "Menu",
    toggle_menu: "Menu",
    back_dashboard: "Back to Dashboard",
    home: "Home",
    clients: "Clients",
    create_client: "Create Client",
    saved_clients: "Saved Clients",
    invoices: "Invoices",
    create_invoice: "Create Invoice",
    saved_invoices: "Saved Invoices",
    quotes: "Quotes",
    create_quote: "Create Quote",
    saved_quotes: "Saved Quotes",
    contracts: "Contracts",
    create_contract: "Create Contract",
    saved_contracts: "Saved Contracts",
    reminders: "Reminders",
    create_reminder: "Create Reminder",
    saved_reminders: "Saved Reminders",
    expense_csv: "Expense CSV",
    create_expense: "Create Expense",
    saved_expenses: "Saved Expenses",
    analytics: "Analytics",
    my_bookkeeper: "My Bookkeeper",
    summary: "Summary",
    roi_estimator: "ROI Estimator",
    tax_assistant: "Tax Assistant",
    tax_calculator: "Tax Calculator",
    tax_analytics: "Tax Analytics",
    tax_guide: "Tax Guide",
    templates: "Templates",
    email_gemeente: "Email to Gemeente",
    cv_portfolio: "CV / Portfolio",
    ai_assistant: "AI Assistant (PRO)",
    settings: "Settings",
    profile: "Profile",
    toggle_theme: "Toggle Theme",
    help: "Help",
    upgrade_pro: "Upgrade to PRO",
    contact_support: "Contact Support",
    logout: "Logout",
    welcome: "Welcome",
    plan_free: "Free",
    quick_clients: "Clients",
    quick_invoice: "Invoice",
    quick_quote: "Quote",
    quick_contract: "Contract",
    quick_reminder: "Reminder",
    revenue: "Revenue",
    unpaid: "Unpaid",
    quote_rate: "Quote Win-Rate",
    reminders_sent: "Reminders Sent",
    expenses: "Expenses",
    overdue: "Overdue",
    top_client: "Top Client",
    smart_suggestions: "Smart Suggestions",
    suggestion_all_good: "✅ All good. Keep it up!",
    suggestion_overdue_invoices: "📌 {count} overdue invoices — send reminders.",
    suggestion_no_reminders: "⚠️ Overdue invoices exist but no reminders sent.",
    suggestion_low_winrate: "📉 Low quote win rate — optimize your offers.",
    suggestion_expenses_over: "📊 Expenses exceed revenue this month.",
    recent_activity: "Recent Activity",
    loading: "Loading...",
    chart_title: "Revenue",
    chart_labels: {
      draft: "Draft",
      sent: "Sent",
      paid: "Paid",
      overdue: "Overdue"
    },
    activity_types: {
      navigation: "Navigation",
      invoice: "Invoice",
      event: "Event"
    },
    activity_messages: {
      "created clients": "Created clients",
      "created reminder": "Created reminder",
      "invoice inv-2025-027 updated": "Invoice INV-2025-027 updated"
    }
  },

  nl: {
    menu: "Menu",
    toggle_menu: "Menu",
    back_dashboard: "Terug naar dashboard",
    home: "Home",
    clients: "Klanten",
    create_client: "Klant aanmaken",
    saved_clients: "Opgeslagen klanten",
    invoices: "Facturen",
    create_invoice: "Factuur aanmaken",
    saved_invoices: "Opgeslagen facturen",
    quotes: "Offertes",
    create_quote: "Offerte aanmaken",
    saved_quotes: "Opgeslagen offertes",
    contracts: "Contracten",
    create_contract: "Contract aanmaken",
    saved_contracts: "Opgeslagen contracten",
    reminders: "Herinneringen",
    create_reminder: "Herinnering aanmaken",
    saved_reminders: "Opgeslagen herinneringen",
    expense_csv: "Onkosten CSV",
    create_expense: "Maak kosten aan",
    saved_expenses: "Opgeslagen kosten",
    analytics: "Analytics",
    my_bookkeeper: "Mijn boekhouder",
    summary: "Overzicht",
    roi_estimator: "ROI-calculator",
    tax_assistant: "Belastingassistent",
    tax_calculator: "Belastingcalculator",
    tax_analytics: "Belastinganalyse",
    tax_guide: "Belastinggids",
    templates: "Sjablonen",
    email_gemeente: "E-mail naar gemeente",
    cv_portfolio: "CV / Portfolio",
    ai_assistant: "AI Assistent (PRO)",
    settings: "Instellingen",
    profile: "Profiel",
    toggle_theme: "Thema wisselen",
    help: "Hulp",
    upgrade_pro: "Upgraden naar PRO",
    contact_support: "Neem contact op met Support",
    logout: "Uitloggen",
    welcome: "Welkom",
    plan_free: "Gratis",
    quick_clients: "Klanten",
    quick_invoice: "Factuur",
    quick_quote: "Offerte",
    quick_contract: "Contract",
    quick_reminder: "Herinnering",
    revenue: "Inkomsten",
    unpaid: "Onbetaald",
    quote_rate: "Winstpercentage offerte",
    reminders_sent: "Verzonden herinneringen",
    expenses: "Uitgaven",
    overdue: "Achterstallig",
    top_client: "Top klant",
    smart_suggestions: "Slimme suggesties",
    suggestion_all_good: "✅ Alles goed. Ga zo door!",
    suggestion_overdue_invoices: "📌 {count} achterstallige facturen — stuur herinneringen.",
    suggestion_no_reminders: "⚠️ Achterstallige facturen maar geen herinneringen verzonden.",
    suggestion_low_winrate: "📉 Lage offerte-succesratio — optimaliseer je aanbiedingen.",
    suggestion_expenses_over: "📊 Uitgaven overschrijden de inkomsten deze maand.",
    recent_activity: "Recente activiteit",
    loading: "Laden...",
    chart_title: "Inkomsten",
    chart_labels: {
      draft: "Concept",
      sent: "Verzonden",
      paid: "Betaald",
      overdue: "Achterstallig"
    },
    activity_types: {
      navigation: "Navigatie",
      invoice: "Factuur",
      event: "Gebeurtenis"
    },
    activity_messages: {
      "created clients": "Klanten aangemaakt",
      "created reminder": "Herinnering aangemaakt",
      "invoice inv-2025-027 updated": "Factuur INV-2025-027 bijgewerkt"
    }
  },
de: {
  menu: "Menü",
  toggle_menu: "Menü",
  back_dashboard: "Zurück zum Dashboard",
  home: "Startseite",
  clients: "Kunden",
  create_client: "Kunde erstellen",
  saved_clients: "Gespeicherte Kunden",
  invoices: "Rechnungen",
  create_invoice: "Rechnung erstellen",
  saved_invoices: "Gespeicherte Rechnungen",
  quotes: "Angebote",
  create_quote: "Angebot erstellen",
  saved_quotes: "Gespeicherte Angebote",
  contracts: "Verträge",
  create_contract: "Vertrag erstellen",
  saved_contracts: "Gespeicherte Verträge",
  reminders: "Erinnerungen",
  create_reminder: "Erinnerung erstellen",
  saved_reminders: "Gespeicherte Erinnerungen",
  expense_csv: "Ausgaben CSV",
  create_expense: "Ausgabe erstellen",
  saved_expenses: "Gespeicherte Ausgaben",
  analytics: "Analyse",
  my_bookkeeper: "Mein Buchhalter",
  summary: "Übersicht",
  roi_estimator: "ROI-Schätzer",
  tax_assistant: "Steuerassistent",
  tax_calculator: "Steuerrechner",
  tax_analytics: "Steueranalyse",
  tax_guide: "Steuerleitfaden",
  templates: "Vorlagen",
  email_gemeente: "E-Mail an Gemeinde",
  cv_portfolio: "Lebenslauf / Portfolio",
  ai_assistant: "KI-Assistent (PRO)",
  settings: "Einstellungen",
  profile: "Profil",
  toggle_theme: "Design wechseln",
  help: "Hilfe",
  upgrade_pro: "Upgrade auf PRO",
  contact_support: "Support kontaktieren",
  logout: "Abmelden",
  welcome: "Willkommen",
  plan_free: "Kostenlos",
  quick_clients: "Kunden",
  quick_invoice: "Rechnung",
  quick_quote: "Angebot",
  quick_contract: "Vertrag",
  quick_reminder: "Erinnerung",
  revenue: "Umsatz",
  unpaid: "Unbezahlt",
  quote_rate: "Annahmequote Angebote",
  reminders_sent: "Gesendete Erinnerungen",
  expenses: "Ausgaben",
  overdue: "Überfällig",
  top_client: "Top-Kunde",
  smart_suggestions: "Smarte Vorschläge",
  suggestion_all_good: "✅ Alles gut. Weiter so!",
  suggestion_overdue_invoices: "📌 {count} überfällige Rechnungen — Erinnerung senden.",
  suggestion_no_reminders: "⚠️ Überfällige Rechnungen vorhanden, aber keine Erinnerungen gesendet.",
  suggestion_low_winrate: "📉 Geringe Angebotsannahme — optimiere deine Angebote.",
  suggestion_expenses_over: "📊 Ausgaben übersteigen Einnahmen in diesem Monat.",
  recent_activity: "Letzte Aktivitäten",
  loading: "Lade...",
  chart_title: "Umsatz",
  chart_labels: {
    draft: "Entwurf",
    sent: "Gesendet",
    paid: "Bezahlt",
    overdue: "Überfällig"
  },
  activity_types: {
    navigation: "Navigation",
    invoice: "Rechnung",
    event: "Ereignis"
  },
  activity_messages: {
    "created clients": "Kunden erstellt",
    "created reminder": "Erinnerung erstellt",
    "invoice inv-2025-027 updated": "Rechnung INV-2025-027 aktualisiert"
  }
},
  fr: {
  menu: "Menu",
  toggle_menu: "Menu",
  back_dashboard: "Retour au tableau de bord",
  home: "Accueil",
  clients: "Clients",
  create_client: "Créer un client",
  saved_clients: "Clients enregistrés",
  invoices: "Factures",
  create_invoice: "Créer une facture",
  saved_invoices: "Factures enregistrées",
  quotes: "Devis",
  create_quote: "Créer un devis",
  saved_quotes: "Devis enregistrés",
  contracts: "Contrats",
  create_contract: "Créer un contrat",
  saved_contracts: "Contrats enregistrés",
  reminders: "Rappels",
  create_reminder: "Créer un rappel",
  saved_reminders: "Rappels enregistrés",
  expense_csv: "Dépenses CSV",
  create_expense: "Créer une dépense",
  saved_expenses: "Dépenses enregistrées",
  analytics: "Analytique",
  my_bookkeeper: "Mon comptable",
  summary: "Résumé",
  roi_estimator: "Calculateur de ROI",
  tax_assistant: "Assistant fiscal",
  tax_calculator: "Calculateur d'impôts",
  tax_analytics: "Analyse fiscale",
  tax_guide: "Guide fiscal",
  templates: "Modèles",
  email_gemeente: "Email à la commune",
  cv_portfolio: "CV / Portfolio",
  ai_assistant: "Assistant IA (PRO)",
  settings: "Paramètres",
  profile: "Profil",
  toggle_theme: "Changer de thème",
  help: "Aide",
  upgrade_pro: "Passer en PRO",
  contact_support: "Contacter le support",
  logout: "Déconnexion",
  welcome: "Bienvenue",
  plan_free: "Gratuit",
  quick_clients: "Clients",
  quick_invoice: "Facture",
  quick_quote: "Devis",
  quick_contract: "Contrat",
  quick_reminder: "Rappel",
  revenue: "Revenus",
  unpaid: "Impayé",
  quote_rate: "Taux d'acceptation",
  reminders_sent: "Rappels envoyés",
  expenses: "Dépenses",
  overdue: "En retard",
  top_client: "Meilleur client",
  smart_suggestions: "Suggestions intelligentes",
  suggestion_all_good: "✅ Tout va bien. Continuez comme ça !",
  suggestion_overdue_invoices: "📌 {count} factures en retard — envoyez des rappels.",
  suggestion_no_reminders: "⚠️ Factures en retard mais aucun rappel envoyé.",
  suggestion_low_winrate: "📉 Taux d'acceptation faible — optimisez vos devis.",
  suggestion_expenses_over: "📊 Les dépenses dépassent les revenus ce mois-ci.",
  recent_activity: "Activité récente",
  loading: "Chargement...",
  chart_title: "Revenus",
  chart_labels: {
    draft: "Brouillon",
    sent: "Envoyée",
    paid: "Payée",
    overdue: "En retard"
  },
  activity_types: {
    navigation: "Navigation",
    invoice: "Facture",
    event: "Événement"
  },
  activity_messages: {
    "created clients": "Clients créés",
    "created reminder": "Rappel créé",
    "invoice inv-2025-027 updated": "Facture INV-2025-027 mise à jour"
  }
},
  pl: {
  menu: "Menu",
  toggle_menu: "Menu",
  back_dashboard: "Powrót do panelu",
  home: "Strona główna",
  clients: "Klienci",
  create_client: "Utwórz klienta",
  saved_clients: "Zapisani klienci",
  invoices: "Faktury",
  create_invoice: "Utwórz fakturę",
  saved_invoices: "Zapisane faktury",
  quotes: "Oferty",
  create_quote: "Utwórz ofertę",
  saved_quotes: "Zapisane oferty",
  contracts: "Kontrakty",
  create_contract: "Utwórz kontrakt",
  saved_contracts: "Zapisane kontrakty",
  reminders: "Przypomnienia",
  create_reminder: "Utwórz przypomnienie",
  saved_reminders: "Zapisane przypomnienia",
  expense_csv: "Wydatki CSV",
  create_expense: "Utwórz wydatek",
  saved_expenses: "Zapisane wydatki",
  analytics: "Analityka",
  my_bookkeeper: "Mój księgowy",
  summary: "Podsumowanie",
  roi_estimator: "Kalkulator ROI",
  tax_assistant: "Asystent podatkowy",
  tax_calculator: "Kalkulator podatkowy",
  tax_analytics: "Analiza podatkowa",
  tax_guide: "Przewodnik podatkowy",
  templates: "Szablony",
  email_gemeente: "Email do gminy",
  cv_portfolio: "CV / Portfolio",
  ai_assistant: "Asystent AI (PRO)",
  settings: "Ustawienia",
  profile: "Profil",
  toggle_theme: "Zmień motyw",
  help: "Pomoc",
  upgrade_pro: "Ulepsz do PRO",
  contact_support: "Skontaktuj się z pomocą",
  logout: "Wyloguj się",
  welcome: "Witaj",
  plan_free: "Darmowy",
  quick_clients: "Klienci",
  quick_invoice: "Faktura",
  quick_quote: "Oferta",
  quick_contract: "Kontrakt",
  quick_reminder: "Przypomnienie",
  revenue: "Przychód",
  unpaid: "Nieopłacone",
  quote_rate: "Wskaźnik akceptacji ofert",
  reminders_sent: "Wysłane przypomnienia",
  expenses: "Wydatki",
  overdue: "Zaległe",
  top_client: "Najlepszy klient",
  smart_suggestions: "Inteligentne sugestie",
  suggestion_all_good: "✅ Wszystko w porządku. Tak trzymaj!",
  suggestion_overdue_invoices: "📌 {count} zaległych faktur — wyślij przypomnienia.",
  suggestion_no_reminders: "⚠️ Są zaległe faktury, ale nie wysłano przypomnień.",
  suggestion_low_winrate: "📉 Niski wskaźnik akceptacji ofert — zoptymalizuj swoje propozycje.",
  suggestion_expenses_over: "📊 Wydatki przekraczają przychód w tym miesiącu.",
  recent_activity: "Ostatnia aktywność",
  loading: "Ładowanie...",
  chart_title: "Przychód",
  chart_labels: {
    draft: "Szkic",
    sent: "Wysłana",
    paid: "Opłacona",
    overdue: "Zaległa"
  },
  activity_types: {
    navigation: "Nawigacja",
    invoice: "Faktura",
    event: "Zdarzenie"
  },
  activity_messages: {
    "created clients": "Utworzono klientów",
    "created reminder": "Utworzono przypomnienie",
    "invoice inv-2025-027 updated": "Zaktualizowano fakturę INV-2025-027"
  }
},
 

 ru: {
  menu: "Меню",
  toggle_menu: "Меню",
  back_dashboard: "Назад к панели",
  home: "Главная",
  clients: "Клиенты",
  create_client: "Создать клиента",
  saved_clients: "Сохранённые клиенты",
  invoices: "Счета",
  create_invoice: "Создать счёт",
  saved_invoices: "Сохранённые счета",
  quotes: "Предложения",
  create_quote: "Создать предложение",
  saved_quotes: "Сохранённые предложения",
  contracts: "Контракты",
  create_contract: "Создать контракт",
  saved_contracts: "Сохранённые контракты",
  reminders: "Напоминания",
  create_reminder: "Создать напоминание",
  saved_reminders: "Сохранённые напоминания",
  expense_csv: "CSV расходов",
  create_expense: "Добавить расход",
  saved_expenses: "Сохранённые расходы",
  analytics: "Аналитика",
  my_bookkeeper: "Мой бухгалтер",
  summary: "Сводка",
  roi_estimator: "Оценка ROI",
  tax_assistant: "Налоговый помощник",
  tax_calculator: "Налоговый калькулятор",
  tax_analytics: "Налоговая аналитика",
  tax_guide: "Налоговое руководство",
  templates: "Шаблоны",
  email_gemeente: "Письмо в муниципалитет",
  cv_portfolio: "Резюме / Портфолио",
  ai_assistant: "ИИ Ассистент (PRO)",
  settings: "Настройки",
  profile: "Профиль",
  toggle_theme: "Сменить тему",
  help: "Помощь",
  upgrade_pro: "Обновить до PRO",
  contact_support: "Связаться с поддержкой",
  logout: "Выйти",
  welcome: "Добро пожаловать",
  plan_free: "Бесплатно",
  quick_clients: "Клиенты",
  quick_invoice: "Счёт",
  quick_quote: "Предложение",
  quick_contract: "Контракт",
  quick_reminder: "Напоминание",
  revenue: "Доход",
  unpaid: "Неоплаченные",
  quote_rate: "Коэф. успеха предложений",
  reminders_sent: "Отправлено напоминаний",
  expenses: "Расходы",
  overdue: "Просрочено",
  top_client: "Лучший клиент",
  smart_suggestions: "Умные советы",
  suggestion_all_good: "✅ Всё отлично. Так держать!",
  suggestion_overdue_invoices: "📌 {count} просроченных счетов — отправьте напоминания.",
  suggestion_no_reminders: "⚠️ Есть просроченные счета, но напоминания не отправлены.",
  suggestion_low_winrate: "📉 Низкий уровень принятия предложений — оптимизируйте их.",
  suggestion_expenses_over: "📊 Расходы превышают доход в этом месяце.",
  recent_activity: "Последняя активность",
  loading: "Загрузка...",
  chart_title: "Доход",
  chart_labels: {
    draft: "Черновик",
    sent: "Отправлен",
    paid: "Оплачен",
    overdue: "Просрочен"
  },
  activity_types: {
    navigation: "Навигация",
    invoice: "Счёт",
    event: "Событие"
  },
  activity_messages: {
    "created clients": "Клиенты созданы",
    "created reminder": "Напоминание создано",
    "invoice inv-2025-027 updated": "Счёт INV-2025-027 обновлён"
  }
},
 es: {
  menu: "Menú",
  toggle_menu: "Menú",
  back_dashboard: "Volver al Panel",
  home: "Inicio",
  clients: "Clientes",
  create_client: "Crear Cliente",
  saved_clients: "Clientes Guardados",
  invoices: "Facturas",
  create_invoice: "Crear Factura",
  saved_invoices: "Facturas Guardadas",
  quotes: "Presupuestos",
  create_quote: "Crear Presupuesto",
  saved_quotes: "Presupuestos Guardados",
  contracts: "Contratos",
  create_contract: "Crear Contrato",
  saved_contracts: "Contratos Guardados",
  reminders: "Recordatorios",
  create_reminder: "Crear Recordatorio",
  saved_reminders: "Recordatorios Guardados",
  expense_csv: "Gastos CSV",
  create_expense: "Crear Gasto",
  saved_expenses: "Gastos Guardados",
  analytics: "Analítica",
  my_bookkeeper: "Mi Contable",
  summary: "Resumen",
  roi_estimator: "Estimador de ROI",
  tax_assistant: "Asistente Fiscal",
  tax_calculator: "Calculadora de Impuestos",
  tax_analytics: "Análisis Fiscal",
  tax_guide: "Guía Fiscal",
  templates: "Plantillas",
  email_gemeente: "Correo a Municipio",
  cv_portfolio: "CV / Portafolio",
  ai_assistant: "Asistente AI (PRO)",
  settings: "Configuración",
  profile: "Perfil",
  toggle_theme: "Cambiar Tema",
  help: "Ayuda",
  upgrade_pro: "Actualizar a PRO",
  contact_support: "Contactar Soporte",
  logout: "Cerrar Sesión",
  welcome: "Bienvenido",
  plan_free: "Gratis",
  quick_clients: "Clientes",
  quick_invoice: "Factura",
  quick_quote: "Presupuesto",
  quick_contract: "Contrato",
  quick_reminder: "Recordatorio",
  revenue: "Ingresos",
  unpaid: "No Pagado",
  quote_rate: "Tasa de Aceptación",
  reminders_sent: "Recordatorios Enviados",
  expenses: "Gastos",
  overdue: "Vencido",
  top_client: "Mejor Cliente",
  smart_suggestions: "Sugerencias Inteligentes",
  suggestion_all_good: "✅ Todo bien. ¡Sigue así!",
  suggestion_overdue_invoices: "📌 {count} facturas vencidas — envía recordatorios.",
  suggestion_no_reminders: "⚠️ Hay facturas vencidas pero no se han enviado recordatorios.",
  suggestion_low_winrate: "📉 Baja tasa de aceptación — optimiza tus ofertas.",
  suggestion_expenses_over: "📊 Los gastos superan los ingresos este mes.",
  recent_activity: "Actividad Reciente",
  loading: "Cargando...",
  chart_title: "Ingresos",
  chart_labels: {
    draft: "Borrador",
    sent: "Enviado",
    paid: "Pagado",
    overdue: "Vencido"
  },
  activity_types: {
    navigation: "Navegación",
    invoice: "Factura",
    event: "Evento"
  },
  activity_messages: {
    "created clients": "Clientes creados",
    "created reminder": "Recordatorio creado",
    "invoice inv-2025-027 updated": "Factura INV-2025-027 actualizada"
  }
}
   }

// 🧠 Apply Translations
function applyTranslations(lang = "en") {
  const dict = window.translations[lang] || window.translations["en"];
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) el.textContent = dict[key];
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const selectedLang = localStorage.getItem("language") || "en";
  applyTranslations(selectedLang);

  const langSelector = document.getElementById("languageSwitcher");
  if (langSelector) {
    langSelector.value = selectedLang;
    langSelector.addEventListener("change", function () {
      localStorage.setItem("language", this.value);
      location.reload();
    });
  }
});
